version: 2
jobs:
  build:
    docker:
      - image: circleci/rust:buster
    
    steps:
      - checkout       # Checks out the repository
      - restore_cache: # Restores our build objects
        key: v1-pitboss-{{ .Environment.CIRCLE_SHA1 }}

      - run:
        name: "Install libmysqlclient-dev"
        command: |
          sudo apt update
          sudo apt install -Y default-libmysqlclient-dev

      - run:
        name: "Print Cargo version"
        command: |
          cargo --version

      - run:
        name: "Print rustc version"
        command: |
          rustc --version

      - run:
        name: "Change dir to repository and build project (Dev mode)"
        command: |
          cd ~/pitboss
          cargo build

      - save_cache: # Caches our build objects with a cache key
        key: v1-pitboss-{{ .Environment.CIRCLE_SHA1 }}
        paths: - ~/pitboss/target
